#! /bin/sh
#
# cryptodisks	Now that all block devices should be available, setup
#		encrypted block devices

### BEGIN INIT INFO
# Provides:          cryptdisks
# Required-Start:    checkroot
# Required-Stop:     umountroot
# Should-Start:      udev devfsd raid2 mdadm lvm
# Should-Stop:
# Default-Start:     S
# Default-Stop:      0 6
### END INIT INFO

CRYPTCMD=/sbin/cryptsetup
DEVMAPCMD=/sbin/dmsetup
TABFILE=/etc/crypttab
MAPPER=/dev/mapper

test -x $CRYPTCMD  || exit 0
test -x $DEVMAPCMD || exit 0
test -f $TABFILE   || exit 0             

[ -r /etc/default/cryptdisks ] && . /etc/default/cryptdisks

case "$CRYPTDISKS_ENABLE" in
        [Nn]*)
                exit 0
                ;;
esac

$DEVMAPCMD mknodes

case "$1" in
start)
	echo -n "Starting crypto disks:"
	egrep -v "^[[:space:]]*(#|$)" $TABFILE | while read dst src key opt; do
		echo -n " $dst"
		if test -b $MAPPER/$dst; then
			echo -n "(running)"
		else
			echo -n "(starting)"
			if [ "x$key" != "x" ] && [ "x$key" != "xnone" ]; then
				INTERACTIVE="no"
				if test -e "$key" ; then
					MODE=`ls -l $key | sed 's/^....\(......\).*/\1/'`
					OWNER=`ls -l $key | sed 's/^[^ ]* *[^ ]* *\([^ ]*\).*/\1/'`
					if test "$MODE" != "------" && \
					   test "$key" != "/dev/urandom"  && \
					   test "$key" != "/dev/hwrandom" && \
					   test "$key" != "/dev/random"; then
						echo " - INSECURE MODE FOR $key" >&2
					fi
					if test $OWNER != root; then
						echo " - INSECURE OWNER FOR $key" >&2
					fi
				else
					echo " - Keyfile for $dst not found, skipping" >&2
					continue
				fi
			else
				INTERACTIVE="yes"
				echo "..."
			fi

			PARAMS=""
			RETRY="no"
			POSTCHECK=""
			PRECHECK=""
			MAKETMP=""
			MAKESWAP=""
			USELUKS=""
			SKIP=""

			# Parse the options field, convert to cryptsetup parameters
			# and contruct the command line
			while test "x$opt" != "x" ; do
				ARG=${opt/,*}
				opt=${opt##$ARG}
				opt=${opt##,}
				PARAM=`echo $ARG | sed "s/=.*//"`
				VALUE=${ARG##$PARAM=}
				
				case "$ARG" in
					*=*)
						PARAM=${ARG/=*}
						VALUE=${ARG##$PARAM=}
						;;
					*)
						PARAM=$ARG
						VALUE=""
				esac
				
				case "$PARAM" in 
					readonly)
						PARAMS="$PARAMS -r"
						;;
					cipher)
						PARAMS="$PARAMS -c $VALUE"
						if test "x$VALUE" = "x" ; then
							echo " - no value for cipher option, skipping" >&2
							SKIP="yes"
						fi
						;;
					size)
						PARAMS="$PARAMS -s $VALUE"
						if test "x$VALUE" = "x" ; then
							echo " - no value for size option, skipping" >&2
							SKIP="yes"
						fi
						;;
					hash)
						PARAMS="$PARAMS -h $VALUE"
						if test "x$VALUE" = "x" ; then
							echo " - no value for hash option, skipping" >&2
							SKIP=yes
						fi
						;;
					verify)
						PARAMS="$PARAMS -y"
						;;
					postcheck)
						if test "x$VALUE" = "x" ; then
							POSTCHECK="$CRYPTDISKS_POSTCHECK"
						else
							POSTCHECK="$VALUE"
						fi
						;;
					precheck)
						if test "x$VALUE" = "x" ; then
							PRECHECK="$CRYPTDISKS_PRECHECK"
						else
							PRECHECK="$VALUE"
						fi
						;;
					retry)
						if test "x$VALUE" = "x" ; then
							RETRY="$CRYPTDISKS_RETRY"
						else
							RETRY="$VALUE"
						fi
						;;
					swap)
						MAKESWAP=yes
						;;
					tmp)
						MAKETMP=yes
						;;
					luks)
						USELUKS=yes
				esac
			done

			if [ "$RETRY" != "no" ] ; then
				case "$RETRY" in
					[0-9]*)
					;;
					*)
						echo " - option RETRY is wrongly set to $RETRY - forced to 'no' " >&2
						RETRY="no"
					;;
				esac
			fi
			if [ "$POSTCHECK" -a -x /usr/share/cryptsetup/postchecks/"$POSTCHECK"  ] ; then
				POSTCHECK="/usr/share/cryptsetup/postchecks/$POSTCHECK"
			fi
			if [ "$PRECHECK" -a -x /usr/share/cryptsetup/prechecks/"$PRECHECK"  ] ; then
				PRECHECK="/usr/share/cryptsetup/prechecks/$PRECHECK"
			fi

			# Set up loopback devices
			if test -f "$src" ; then
				test -d /sys/block/loop0 || modprobe loop || SKIP=yes
				LOOP_ID=
				for i in 0 1 2 3 4 5 6 7 ; do
					if test "x`cat /sys/block/loop$i/size`" = "x0" ; then
						LOOP_ID=$i
						break
					fi
				done
				if test "x$LOOP_ID" = "x" ; then
					SKIP=yes
				else
					losetup /dev/loop$LOOP_ID $src || SKIP=yes
					src=/dev/loop$LOOP_ID
				fi
			fi

			if test "x$SKIP" = "xyes" ; then
				continue
			fi

			# Password processing in luks* from cryptsetup is newline sensitive
			# reading stops after \n is received!
			if test "x$USELUKS" = "xyes" && \
			   test "x$MAKESWAP" = "xyes" && \
			   test "x$INTERACTIVE" != "xyes"; then
				echo -e "\n - you should not mix swap and luks, skipping" >&2
				continue
			fi

			if test "x$USELUKS" = "xyes" && $CRYPTCMD isLuks $src ; then
				if [ "$PRECHECK" = "" ] || $PRECHECK $src; then
					while [ "x$RETRY" = xno ]  || [ "$RETRY" -gt 0 ] ; do
						if test "x$INTERACTIVE" = "xyes" ; then
							$CRYPTCMD $PARAMS luksOpen $src $dst <&1
							RESULT=$?
						else
							$CRYPTCMD $PARAMS luksOpen $src $dst --key-file $key <&1
							RESULT=$?
						fi
						if [ $RESULT = 0 ] ; then
							if [ "$POSTCHECK" = ""  ] || $POSTCHECK $MAPPER/$dst ; then
								break
							else
								echo " - the postcheck for '$MAPPER/$dst' failed - maybe the password is wrong" >&2
								echo " - removing the crypto device $dst" >&2
								$CRYPTCMD luksClose $dst
								sleep 1
							fi
						fi
						test "x$RETRY" = "xno" && break
						RETRY=`expr $RETRY - 1`
						[ $RETRY -gt 0 ] && echo " - retrying for $dst"
					done
				else
					echo " - the precheck for '$src' failed" >&2
				fi
							
			else
				if [ "$PRECHECK" = "" ] || $PRECHECK $src; then
					while [ "x$RETRY" = xno ]  || [ "$RETRY" -gt 0 ] ; do
						if test "x$INTERACTIVE" = "xyes" ; then
							$CRYPTCMD $PARAMS create $dst $src <&1
							RESULT=$?
						else
							$CRYPTCMD $PARAMS -d $key create $dst $src
							RESULT=$?
						fi
						# test : echo RESULT $RESULT
						if [ $RESULT = 0 ] ; then
							if [ "$POSTCHECK" = ""  ] || $POSTCHECK $MAPPER/$dst ; then
								break
							else
								echo " - the postcheck for '$MAPPER/$dst' failed - maybe the password is wrong" >&2
								echo " - removing the crypto device $dst" >&2
								$CRYPTCMD remove $dst
								sleep 1
							fi
						fi
						test "x$RETRY" = "xno" && break
						RETRY=`expr $RETRY - 1`
						[ $RETRY -gt 0 ] && echo " - retrying for $dst"
					done
				else
					echo " - the precheck for '$src' failed" >&2
					sleep 1
				fi
			fi

			if test "x$MAKESWAP" = "xyes" && test -b $MAPPER/$dst; then
				mkswap $MAPPER/$dst 2>/dev/null >/dev/null
			fi

			if test "x$MAKETMP" = "xyes" && test -b $MAPPER/$dst; then
				mke2fs $MAPPER/$dst 2>/dev/null >/dev/null
				mount -t ext2 $MAPPER/$dst /tmp
				chmod 1777 /tmp
				umount /tmp
			fi
		fi
	done
	echo "."
	;;
stop)
	echo -n "Stopping crypto disks:"
	egrep -v "^[[:space:]]*(#|$)" $TABFILE | while read dst src key; do
		echo -n " $dst"
		if test -b $MAPPER/$dst; then
			if $DEVMAPCMD info $dst | grep -q '^Open count: *0$'; then
				dev=`$DEVMAPCMD table $dst | sed 's/^.* \([0-9]*:[0-9]*\) .*/\1/'`
				major=`echo $dev | sed 's/:.*//'`
				minor=`echo $dev | sed 's/.*://'`
				
				echo -n "(stopping)"
				$CRYPTCMD remove $dst
				
				# Detach loopback device, if attached
				if test -f $src -a $major -eq 7; then
					losetup -d /dev/loop$minor
				fi
			else
				echo -n "(busy)"
			fi
		else
			echo -n "(stopped)"
		fi
	done

	echo "."
	;;
restart|reload|force-reload)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart|reload|force-reload}"
	;;
esac
