#! /bin/sh

version="1.2.0"

while test $# -gt 0; do
    case "$1" in
	--*=*)
	    optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	    ;;
	*)
	    optarg=""
	    ;;
    esac

    case $1 in
	--version)
	    echo_version=yes
	    ;;
        --api-version)
            echo_api_version=yes
            ;;
	--libs)
	    echo_libs=yes
	    ;;
    esac
    shift
done

if test "$echo_libs" = "yes"; then
    echo /usr/lib/libgcrypt.a /usr/lib/libgpg-error.a
fi

if test "$echo_version" = "yes"; then
    echo 1.2.0
fi

if test "$echo_api_version" = "yes"; then
    echo 1
fi
