#! /bin/sh -e

case "$1" in
  configure)
    update-rc.d cryptdisks start 28 S . stop 48 0 6 . >/dev/null
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "postinst called with unknown argument '$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
