#!/bin/sh
# this script depends on /lib/udev/vol_id from the udev package

if test ! -x "/lib/udev/vol_id"; then
  echo -e "\n - WARNING: vol_id from udev is not available, impossible to run checks."
  exit 0
fi

dev=$1
fs=$2

vol_id=`/lib/udev/vol_id -t $dev 2>&1`

if test "$vol_id" = "$dev: unknown volume type"; then
  if test -z "$fs"; then
    echo -e "\n - The device $dev does not contain a known filesystem."
    exit 1
  elif test "$fs" = "none"; then
    echo -e "\n - The device $dev contains the valid filesystem type $vol_id."
    exit 1
  fi
elif test -n "$fs" -a "$vol_id" != "$fs"; then
  echo -e "\n - The device $dev does not contain a filesystem type $fs."
  exit 1
fi
