#!/bin/sh

# cryptdisks_start - wrapper around cryptsetup which parses
# /etc/crypttab, just like mount parses /etc/fstab.

# Initial code and (c) 2007 Jon Dowland <jon@alcopop.org>
# License: GNU General Public License, v2 or any later
# (http://www.gnu.org/copyleft/gpl.html)

set -e

if [ $# -lt 1 ]; then
	echo "usage: $0 <name>" >&2
	echo >&2
	echo "reads /etc/crypttab and starts the mapping corresponding to <name>" >&2
	exit 1
fi

if [ -r /lib/cryptsetup/cryptdisks.functions ]; then
	. /lib/cryptsetup/cryptdisks.functions
else
	exit 0
fi

log_action_begin_msg "Starting crypto disk"
mount_fs

egrep -v "^[[:space:]]*(#|$)" "$TABFILE" | while read dst src key opts; do
	if [ "$1" = "$dst" ]; then
		handle_crypttab_line_start "$dst" "$src" "$key" "$opts" <&3
		exit 0
	fi
done 3<&1

umount_fs
log_action_end_msg 0
