#!/bin/sh

# cryptdisks_stop - wrapper around cryptsetup which parses
# /etc/crypttab, just like mount parses /etc/fstab.

# Initial code stolen from cryptdisks_start by Jon Dowland <jon@alcopop.org>
# Copyright (C) 2008 by Jonas Meurer <jonas@freesources.org>
# License: GNU General Public License, v2 or any later
# (http://www.gnu.org/copyleft/gpl.html)

set -e

if [ $# -lt 1 ]; then
	echo "usage: $0 <name>" >&2
	echo >&2
	echo "reads /etc/crypttab and stops the mapping corresponding to <name>" >&2
	exit 1
fi

if [ -r /lib/cryptsetup/cryptdisks.functions ]; then
	. /lib/cryptsetup/cryptdisks.functions
else
	exit 0
fi

LOUD="yes"

log_action_begin_msg "Stopping crypto disk"

count=0
tablen="$(egrep -v "^[[:space:]]*(#|$)" "$TABFILE" | /usr/bin/wc -l)"
egrep -v "^[[:space:]]*(#|$)" "$TABFILE" | while read dst src key opts; do
	count=$(( $count + 1 ))
	if [ "$1" = "$dst" ]; then
		ret=0
		handle_crypttab_line_stop "$dst" "$src" "$key" "$opts" <&3 || ret=$?
	elif [ $count -ge $tablen ]; then
		ret=1
		device_msg "$1" "failed, not found in crypttab"
	fi
	log_action_end_msg $ret
done 3<&1
