#!/bin/sh

# cryptdisks_start - wrapper around cryptsetup which parses
# /etc/crypttab, just like mount parses /etc/fstab.

# Initial code and (c) 2007 Jon Dowland <jon@alcopop.org>
# License: GNU General Public License, v2 or any later
# (https://www.gnu.org/copyleft/gpl.html)

set -e

if [ $# -lt 1 ]; then
    echo "usage: $0 <name>" >&2
    echo >&2
    echo "reads /etc/crypttab and starts the mapping corresponding to <name>" >&2
    exit 1
fi

. /lib/cryptsetup/cryptdisks.functions

INITSTATE="manual"
DEFAULT_LOUD="yes"
FORCE_START="yes"

if [ $(id -u) -ne 0 ]; then
    log_warning_msg "$0 needs root privileges"
    exit 1
fi

log_action_begin_msg "Starting crypto disk"
mount_fs

rv=0
for name in "$@"; do
    if ! crypttab_find_target "$name"; then
        device_msg "$name" "failed, not found in crypttab"
        rv=1
    else
        setup_mapping "$CRYPTTAB_NAME" "$CRYPTTAB_SOURCE" "$CRYPTTAB_KEY" "$CRYPTTAB_OPTIONS" || rv=$?
    fi
done
umount_fs

log_action_end_msg $rv
exit $rv
