#!/bin/sh
#
# Script to decrypt the key which is encrypted with openssl.
# See /usr/share/doc/cryptsetup/examples/gen-ssl-key to create such a key.
#

decrypt_ssl () {
	local tries maxtries
	maxtries=3
	tries=0

	echo -e "\nDecrypting ssl key $1..." >&2
	while [ $tries -lt $maxtries ]; do
		if /usr/bin/openssl enc -aes-256-cbc -d -salt -in $1 2> /dev/null 2>&1; then
			break
		fi
		tries=$(( $tries + 1))
	done
	rm -f $tmpkey

	if [ $tries -eq $maxtries ]; then
		echo -e "\nMaximum number of attempts exceeded" >&2
		exit 1
	fi
}

decrypt_ssl $1
