#!/bin/sh

# The default configuration of openct expects its program to be located in
# /usr/sbin and /usr/bin, rather than /bin and /sbin.
# Instead of 'manually' adjust the configuration, we just adjust the path.

PATH="$PATH:/usr/bin:/usr/sbin"

check_reader() {
    readerfound=0

    if [ ! -e "$readertmp" ] ; then
        readertmp=$(mktemp /tmp/decrypt_openct.XXXXXXXX)
    fi

    openct-tool list > $readertmp 2>&1
    if [ $? == 0 ] ; then
        readerfound=1
    fi
}

wait_reader() {
    check_reader
    if [ $readerfound == 0 ] ; then
        echo Waiting for Smart Card reader... >&2
        tries=0
        while [ $readerfound == 0 -a $tries -lt 60 ] ; do
            sleep 1
            check_reader
            tries=$(($tries + 1))
        done
        cat $readertmp >&2
        if [ $readerfound == 0 ] ; then
            echo Failed to find Smart Card reader!
            exit 1
        fi
    fi
    rm $readertmp
}

echo >&2

/usr/sbin/openct-control init
wait_reader

# Due to a bug in openct, the --label does not work on data objects, means,
# all data objects have by default the label 'pkcs15-init', that's why we are
# setting the label manually if none is configured by the user.

if [ -z "$1" ]
then
	LABEL="pkcs15-init"
else
	LABEL="$1"
fi

if [ -n "$PASS" ]
then
	# Non-interactive call, getting pin number from usplash
	pkcs15-tool --read-data-object $LABEL --pin $PASS
else
	# Interactive call, user enters pin
	pkcs15-tool --read-data-object $LABEL
fi

exit $?
